import { arrow, photo, biography, layout } from './shared.mjs';
export const home = () => layout('Thainá Sampaio | Fotografia, beleza e presença', 'Conheça o Pacote Boss, a Mentoria Boss, o Workshop Boss, o Guia de Poses e os cursos Beauty Edit e Luz em Foco.', `
<section class="home-hero" aria-labelledby="hero-title">
  <div class="hero-photo">${photo('beauty-edit-hero-thaina-beauty-edit', 'Retrato em preto e branco de Thainá Sampaio, com luz que valoriza sua expressão', {eager:true, sizes:'(max-width: 700px) 100vw, 62vw'})}</div>
  <div class="hero-copy"><p class="eyebrow"><span class="small-line"></span> POR THAINÁ SAMPAIO</p><h1 id="hero-title">Sua essência.<br>Uma imagem<br><em>inesquecível.</em></h1><p class="hero-description">Maquiagem e fotografia se encontram para revelar a sua melhor versão. Com intenção, personalidade e presença.</p><div class="hero-actions"><a class="button" href="#pacote-boss">Conheça o Pacote Boss ${arrow}</a><a class="text-link" href="#cursos">Explore os produtos <span aria-hidden="true">↗</span></a></div></div>
  <div class="hero-bottom"><span>MAIS QUE UMA FOTO. UMA NOVA FORMA DE SE VER.</span><a href="#pacote-boss" aria-label="Conhecer a experiência">EXPLORE <span>↓</span></a></div>
</section>
<section class="portugal-event" aria-labelledby="portugal-event-title">
  <div class="portugal-event-date" aria-label="25 de fevereiro, em Portugal"><span>25</span><div>FEVEREIRO<br>PORTUGAL</div></div>
  <div class="portugal-event-copy"><p class="eyebrow">EVENTO ESPECIAL · PORTUGAL</p><h2 id="portugal-event-title">Workshop Boss <em>Portugal.</em></h2><p>Uma edição especial e exclusiva do Workshop Boss, realizada em Portugal para viver o método em uma experiência presencial.</p><span>Evento independente do Workshop Boss tradicional, que acontece com mais frequência em nosso espaço.</span></div>
  <a class="button portugal-event-cta" href="#contato" data-whatsapp="Olá, Thainá! Tenho interesse no Workshop Boss especial em Portugal. Pode me passar as informações?">Quero participar ${arrow}</a>
</section>
<div class="statement-strip" aria-hidden="true"><span>BELEZA COM INTENÇÃO</span><i>✳</i><span>IMAGENS QUE POSICIONAM</span><i>✳</i><span>PRESENÇA QUE MARCA</span><i>✳</i></div>
<section class="section light boss-section" id="pacote-boss">
  <div class="boss-visual"><div class="image-frame">${photo('luz-em-foco-grid-luz-em-foco-08', 'Retrato de mulher com blazer marrom, em uma composição de estúdio sofisticada')}</div><span class="image-caption">BELEZA, DIREÇÃO & FOTOGRAFIA</span><span class="vertical-caption">A EXPERIÊNCIA BOSS</span></div>
  <div class="boss-copy"><p class="eyebrow">01 / A SUA PRÓXIMA VERSÃO</p><h2>Você tem presença.<br>Vamos <em>revelá-la.</em></h2><p class="section-intro">Conheça o <strong>Pacote Boss.</strong></p><p>Uma experiência completa para transformar sua imagem em uma expressão de quem você é. Eu cuido da maquiagem, te ajudo a escolher os looks e conduzo cada pose e composição do seu ensaio.</p><p>Você não precisa saber posar. Só precisa chegar com vontade de se enxergar de um novo jeito.</p><div class="experience-steps"><div><span>01</span><p><strong>Beleza que valoriza</strong>Maquiagem feita por mim, pensada para você.</p></div><div><span>02</span><p><strong>Direção em cada detalhe</strong>Auxílio nos looks, nas poses e na composição.</p></div><div><span>03</span><p><strong>Uma imagem com intenção</strong>Retratos que traduzem sua personalidade.</p></div></div><a class="button dark-button" href="#contato" data-whatsapp="Olá, Thainá! Quero viver a experiência do Pacote Boss. Pode me contar como funciona?">Quero viver essa experiência ${arrow}</a></div>
</section>
<section class="portfolio-section light" aria-label="Fotografias por Thainá Sampaio"><div class="portfolio-heading"><p class="eyebrow">CADA PESSOA, UMA NOVA HISTÓRIA.</p><span>Um olhar. Muitas possibilidades.</span></div><div class="portfolio-grid">${photo('luz-em-foco-grid-luz-em-foco-12','Retrato de beleza com maquiagem luminosa e fundo escuro')}${photo('luz-em-foco-grid-luz-em-foco-02','Ensaio em preto e branco com chapéu e alfaiataria')}${photo('luz-em-foco-grid-luz-em-foco-14','Retrato feminino com jaqueta de couro e direção de pose')}${photo('luz-em-foco-grid-luz-em-foco-21','Retrato de estúdio com sombras gráficas')}</div></section>
<section class="section testimonials light" id="depoimentos"><div class="section-heading"><div><p class="eyebrow">02 / QUEM VIVE, SENTE</p><h2>O que fica <em>além da foto.</em></h2></div></div><div class="testimonials-grid">${[
['Lara','Encontramos tudo que precisamos no seu Studio beleza elegância sofisticação e o mais importante carinho atenção cuidado e muito amor!'],
['Sofia','Você tem um dom incrível de deixar a gente à vontade e de fazer com que a gente se sinta bonita de verdade. Foi uma experiência leve, divertida e eu amei o resultado!'],
['Fernanda','Foi um dia de muito aprendizado, inspiração e troca. Dá para perceber o carinho, a dedicação e a paixão que você tem pela fotografia, e isso faz toda a diferença.'],
['Camila','Tirar foto vai além de poses, beleza e roupas. É preciso ter alguém por trás das câmeras e de toda edição como você. Que capta muito além do que o cliente espera.'],
['Ariany','Simplesmente apaixonada! Não teve uma que não gostei!!! Minha primeira experiência foi maravilhosa, obrigada por tudo!'],
['Antônia','Aprendi muito, mas o que mais me marcou foi o seu cuidado e a sua atenção. Você é uma pessoa muito atenciosa, paciente e realmente se importa com cada detalhe e com quem está aprendendo com vc.'],
['Emili','Obrigada pela dedicação e cuidado para que eu estivesse aprendendo. Eu amei tudo desde o atendimento no whats, ao atendimento presencial.'],
['Laís','Eu estou impactada até agora com as Fotos. Você é perfeita!!!!! Muito obrigada'],
['Gabrielle','Muito obrigadaaa, eu amei muito as fotos. Você faz tudo ficar mais leve e tranquilo durante o ensaio. Parabéns pelo trabalho'],
['Thamires','Nossa estou muito apaixonada com o resultado, muito obrigada mesmo por tudooo, ameiiiii, ficou perfeita demais'],
['Paloma','Foi simplesmente maravilhoso e superou todas as minhas expectativas! A recepção de vocês foi incrível, tanto você quanto sua mãe foram muito acolhedoras, me senti em casa.'],
['Rafaela','Queria te agradecer pelo trabalho perfeito que você fez, foi uma experiência totalmente diferente do que eu estava acostumada e eu AMEI. Superou todas as minhas expectativas.'],
['Fernanda','Já fiz várias fotos antes, mas nada se compara ao capricho e à dedicação de vocês. A maquiagem permaneceu impecável até a noite, se eu não tivesse tirado, estaria perfeita até agora!']
].map(([name,quote])=>`<article class="quote-card"><span class="quote-mark" aria-hidden="true">“</span><blockquote>${quote}</blockquote><div class="quote-person"><strong>${name}</strong></div></article>`).join('')}</div></section>
<section class="section courses-section" id="cursos"><div class="section-heading"><div><p class="eyebrow">03 / EXPERIÊNCIAS & FORMAÇÃO</p><h2>Escolha o seu<br><em>próximo passo.</em></h2></div><p>Do ensaio à formação profissional.<br>Experiências, acompanhamento e cursos<br>para transformar a sua imagem e o seu trabalho.</p></div><div class="course-grid product-grid">${[
['pacote-boss','luz-em-foco-grid-luz-em-foco-08','01 / EXPERIÊNCIA FOTOGRÁFICA','Pacote Boss','Maquiagem, direção e fotografia para revelar a sua melhor versão.','Agendar pelo WhatsApp','Olá, Thainá! Quero viver a experiência do Pacote Boss. Pode me contar como funciona?','Retrato de mulher com blazer marrom no estúdio'],
['mentoria-boss','luz-em-foco-thaina-perfil-luz-em-foco','02 / ACOMPANHAMENTO INDIVIDUAL','Mentoria Boss','Eleve sua fotografia, seu posicionamento e o valor do seu trabalho.','Conhecer a mentoria','Olá, Thainá! Tenho interesse na Mentoria Boss individual. Gostaria de saber mais sobre as modalidades online e presencial.','Thainá Sampaio em retrato de corpo inteiro no estúdio'],
['workshop-boss','boss-4p-hero-thaina-boss-4p','03 / CURSO EM GRUPO','Workshop Boss','O workshop tradicional no nosso espaço: uma imersão de teoria e prática para viver o Método Boss.','Entrar na lista de espera','','Thainá Sampaio no estúdio durante uma formação'],
['guia-de-poses','guia-de-poses-card.jpg','04 / PRODUTO DIGITAL','Guia de Poses','Mais de 370 poses em pé, sentada, no chão, close-up e até gestante.','Comprar pelo WhatsApp','Olá, Thainá! Tenho interesse em comprar o Guia de Poses digital. Pode me passar as informações?','Capa do Guia de Poses nas mãos de uma modelo'],
['beauty-edit','beauty-edit-capa-do-beauty-edit','05 / CURSO DE EDIÇÃO','Beauty Edit','O refinamento que transforma uma boa foto em uma imagem extraordinária.','Conhecer o curso','', 'Retrato em preto e branco de mulher com blazer claro e brincos grandes, capa do Beauty Edit'],
['luz-em-foco','luz-em-foco-hero-thaina-luz-em-foco','06 / CURSO DE ILUMINAÇÃO','Luz em Foco','Domine a luz, crie atmosferas e dê uma nova dimensão aos seus retratos.','Conhecer o curso','', 'Thainá Sampaio na apresentação do curso Luz em Foco']
].map(([slug,img,cat,name,desc,cta,message,alt])=>{
  const image = slug === 'guia-de-poses' ? `<img src="/assets/img/${img}" alt="${alt}" width="1066" height="1600" loading="lazy" decoding="async">` : photo(img, alt, {sizes:'(max-width: 760px) 90vw, (max-width: 1100px) 45vw, 33vw'});
  const external = slug === 'workshop-boss' ? 'https://forms.gle/qmJtngYiipNiujeW8' : '';
  const action = external ? `<a class="button button-small product-cta" href="${external}" target="_blank" rel="noopener noreferrer">${cta} ${arrow}</a>` : message ? `<a class="button button-small product-cta" href="#contato" data-whatsapp="${message}">${cta} ${arrow}</a>` : `<a class="button button-small product-cta" href="/${slug}/">${cta} ${arrow}</a>`;
  return `<article class="course-card product-card"><div class="course-image">${image}</div><div class="course-info"><p class="eyebrow">${cat}</p><h3>${name}</h3><p>${desc}</p><div class="product-card-action">${action}</div></div></article>`;
}).join('')}</div></section>
<section class="section light product-feature mentorship-feature" id="mentoria-boss" aria-labelledby="mentoria-title">
  <div class="product-feature-image">${photo('luz-em-foco-thaina-perfil-luz-em-foco','Thainá Sampaio, fotógrafa e mentora, em retrato de corpo inteiro no estúdio',{sizes:'(max-width: 760px) 100vw, 44vw'})}</div>
  <div class="product-feature-copy"><p class="eyebrow">ACOMPANHAMENTO INDIVIDUAL</p><h2 id="mentoria-title">Mentoria <em>Boss.</em></h2><p class="feature-lead">Eleve sua fotografia, seu posicionamento e o valor do seu trabalho.</p><p>A Mentoria Boss é um acompanhamento individual e estratégico para fotógrafos que desejam dominar a fotografia de estúdio, construir ensaios com mais intenção e transformar conhecimento técnico em posicionamento, autoridade e vendas.</p><h3>O que você vai desenvolver</h3><ul class="development-list">${['Posicionamento e autoridade','Consultoria de imagem','Construção e planejamento de ensaios','Direção e poses','Sets de luz em estúdio','Fotografia e composição','Edição avançada','Precificação e criação de pacotes','Atendimento e vendas','Marketing e posicionamento'].map(item=>`<li>${item}</li>`).join('')}</ul><div class="individual-note"><h3>Acompanhamento individual</h3><p>A mentoria é personalizada de acordo com o momento e os objetivos de cada profissional, com direcionamento estratégico e acompanhamento próximo durante todo o processo.</p></div><p class="eyebrow modality-label">DUAS MODALIDADES</p><div class="modality-grid"><article><span>01</span><h3>Online</h3><p>Para quem deseja aprender e desenvolver sua fotografia e seu negócio com acompanhamento individual, de onde estiver.</p></article><article><span>02</span><h3>Presencial</h3><p>Uma experiência prática e imersiva em estúdio, com aplicação dos conhecimentos, construção dos sets de luz, direção e acompanhamento individual.</p></article></div><div class="feature-closing"><h3>Uma experiência para quem quer subir de nível</h3><p>Mais do que aprender a fotografar, a Mentoria Boss ensina a construir uma experiência, uma imagem e um negócio que sejam percebidos pelo valor que entregam.</p></div><a class="button dark-button" href="#contato" data-whatsapp="Olá, Thainá! Tenho interesse na Mentoria Boss individual. Gostaria de saber mais sobre as modalidades online e presencial.">Quero conhecer a Mentoria ${arrow}</a></div>
</section>
<section class="section product-feature workshop-feature" id="workshop-boss" aria-labelledby="workshop-title">
  <div class="product-feature-copy"><p class="eyebrow">EXPERIÊNCIA PRESENCIAL · CURSO EM GRUPO</p><h2 id="workshop-title">Workshop <em>Boss.</em></h2><p class="feature-lead">Uma experiência presencial comigo, no meu estúdio, para fotógrafos que desejam elevar o nível dos seus ensaios e do seu posicionamento.</p><p>O Workshop Boss tradicional acontece com mais frequência em nosso espaço. É um dia de teoria e prática, com sets de luz, direção, poses, consultoria de imagem, posicionamento, precificação, atendimento e vendas.</p><p>Uma imersão para aprender, praticar e viver de perto o Método Boss.</p><div class="workshop-topics">${['Sets de luz','Direção e poses','Consultoria de imagem','Posicionamento','Precificação','Atendimento e vendas'].map(item=>`<span>${item}</span>`).join('')}</div><a class="button" href="https://forms.gle/qmJtngYiipNiujeW8" target="_blank" rel="noopener noreferrer">Entrar na lista de espera ${arrow}</a></div>
  <div class="product-feature-image">${photo('boss-4p-hero-thaina-boss-4p','Thainá Sampaio durante uma experiência de formação em fotografia',{sizes:'(max-width: 760px) 100vw, 44vw'})}<span class="waitlist-label">LISTA DE ESPERA</span></div>
</section>
<section class="section about-section light" id="sobre"><div class="about-copy"><p class="eyebrow">04 / POR TRÁS DAS LENTES</p><h2>Muito prazer,<br><em>Thainá.</em></h2>${biography}<span class="signature">Thainá Sampaio</span><p class="eyebrow">MAQUIADORA, FOTÓGRAFA & MENTORA</p></div><div class="about-image">${photo('beauty-edit-thaina-perfil-beauty-edit','Thainá Sampaio, maquiadora, fotógrafa e criadora do Pacote Boss')}<span class="about-image-label">Um olhar que transforma.</span></div></section>
<section class="section contact-section" id="contato"><div class="contact-copy"><p class="eyebrow">05 / VAMOS CONVERSAR</p><h2>A sua próxima<br>imagem começa<br><em>com um olá.</em></h2><p>Quer agendar seu Pacote Boss ou saber mais sobre algum produto? Me conte o que você tem em mente.</p><a class="text-link" href="#contact-form" data-whatsapp="Olá, Thainá! Vim pelo site e gostaria de conversar.">Fale comigo pelo WhatsApp ${arrow}</a></div><form id="contact-form"><div class="form-row"><label for="name">Seu nome<input id="name" name="name" autocomplete="name" placeholder="Como posso te chamar?" required maxlength="100"></label><label for="phone">Seu WhatsApp<input id="phone" name="phone" type="tel" autocomplete="tel" inputmode="tel" placeholder="(00) 00000-0000" required minlength="10" maxlength="24"></label></div><label for="email">Seu e-mail <span class="optional">(opcional)</span><input id="email" name="email" type="email" autocomplete="email" placeholder="voce@exemplo.com" maxlength="200"></label><label for="interest">Sobre o que vamos conversar?<select id="interest" name="interest" required><option value="">Selecione uma opção</option><option>Pacote Boss — ensaio fotográfico</option><option>Mentoria Boss</option><option>Workshop Boss — lista de espera</option><option>Workshop Boss Portugal — evento especial</option><option>Guia de Poses</option><option>Curso Beauty Edit</option><option>Curso Luz em Foco</option><option>Outros assuntos</option></select></label><label for="message">Sua mensagem<textarea id="message" name="message" rows="3" placeholder="Me conte um pouco sobre você e o que procura…" required maxlength="2000"></textarea></label><p class="form-note">Ao continuar, sua mensagem será preparada no WhatsApp. O envio é feito por você, na conversa.</p><button class="button" type="submit">Continuar no WhatsApp ${arrow}</button><p id="form-status" class="form-status" role="status" aria-live="polite"></p></form></section>
`);
