import { arrow, photo, biography, layout } from './shared.mjs';
export const home = () => layout('Thainá Sampaio | Fotografia, beleza e presença', 'Conheça o Pacote Boss: maquiagem e ensaio fotográfico com Thainá Sampaio. Explore também os cursos Beauty Edit, Boss 4P e Luz em Foco.', `
<section class="home-hero" aria-labelledby="hero-title">
  <div class="hero-photo">${photo('beauty-edit-hero-thaina-beauty-edit', 'Retrato em preto e branco de Thainá Sampaio, com luz que valoriza sua expressão', {eager:true, sizes:'(max-width: 700px) 100vw, 62vw'})}</div>
  <div class="hero-copy"><p class="eyebrow"><span class="small-line"></span> POR THAINÁ SAMPAIO</p><h1 id="hero-title">Sua essência.<br>Uma imagem<br><em>inesquecível.</em></h1><p class="hero-description">Maquiagem e fotografia se encontram para revelar a sua melhor versão. Com intenção, personalidade e presença.</p><div class="hero-actions"><a class="button" href="#pacote-boss">Conheça o Pacote Boss ${arrow}</a><a class="text-link" href="#cursos">Explore os cursos <span aria-hidden="true">↗</span></a></div></div>
  <div class="hero-bottom"><span>MAIS QUE UMA FOTO. UMA NOVA FORMA DE SE VER.</span><a href="#pacote-boss" aria-label="Conhecer a experiência">EXPLORE <span>↓</span></a></div>
</section>
<section class="workshop-boss" id="workshop-boss" aria-labelledby="workshop-boss-title">
  <div class="workshop-boss-date" aria-label="25 de fevereiro, em Portugal"><span>25</span><div>FEVEREIRO<br>PORTUGAL</div></div>
  <div class="workshop-boss-copy"><p class="eyebrow">ENCONTRO PRESENCIAL · PORTUGAL</p><h2 id="workshop-boss-title">Workshop <em>Boss.</em></h2><p>Uma edição especial do Workshop Boss acontece em Portugal no dia 25/02. Quero você lá.</p></div>
  <a class="button workshop-boss-cta" href="#contato" data-whatsapp="Olá, Thainá! Quero garantir minha vaga no Workshop Boss em Portugal no dia 25/02. Pode me passar as informações?">Garanta sua vaga ${arrow}</a>
</section>
<div class="statement-strip" aria-hidden="true"><span>BELEZA COM INTENÇÃO</span><i>✳</i><span>IMAGENS QUE POSICIONAM</span><i>✳</i><span>PRESENÇA QUE MARCA</span><i>✳</i></div>
<section class="section light boss-section" id="pacote-boss">
  <div class="boss-visual"><div class="image-frame">${photo('luz-em-foco-grid-luz-em-foco-08', 'Retrato de mulher com blazer marrom, em uma composição de estúdio sofisticada')}</div><span class="image-caption">BELEZA, DIREÇÃO & FOTOGRAFIA</span><span class="vertical-caption">A EXPERIÊNCIA BOSS</span></div>
  <div class="boss-copy"><p class="eyebrow">01 / A SUA PRÓXIMA VERSÃO</p><h2>Você tem presença.<br>Vamos <em>revelá-la.</em></h2><p class="section-intro">Conheça o <strong>Pacote Boss.</strong></p><p>Uma experiência completa para transformar sua imagem em uma expressão de quem você é. Eu cuido da maquiagem, te ajudo a escolher os looks e conduzo cada pose e composição do seu ensaio.</p><p>Você não precisa saber posar. Só precisa chegar com vontade de se enxergar de um novo jeito.</p><div class="experience-steps"><div><span>01</span><p><strong>Beleza que valoriza</strong>Maquiagem feita por mim, pensada para você.</p></div><div><span>02</span><p><strong>Direção em cada detalhe</strong>Auxílio nos looks, nas poses e na composição.</p></div><div><span>03</span><p><strong>Uma imagem com intenção</strong>Retratos que traduzem sua personalidade.</p></div></div><a class="button dark-button" href="#contato" data-whatsapp="Olá, Thainá! Quero viver a experiência do Pacote Boss. Pode me contar como funciona?">Quero viver essa experiência ${arrow}</a></div>
</section>
<section class="portfolio-section light" aria-label="Fotografias por Thainá Sampaio"><div class="portfolio-heading"><p class="eyebrow">CADA PESSOA, UMA NOVA HISTÓRIA.</p><span>Um olhar. Muitas possibilidades.</span></div><div class="portfolio-grid">${photo('luz-em-foco-grid-luz-em-foco-12','Retrato de beleza com maquiagem luminosa e fundo escuro')}${photo('luz-em-foco-grid-luz-em-foco-02','Ensaio em preto e branco com chapéu e alfaiataria')}${photo('luz-em-foco-grid-luz-em-foco-14','Retrato feminino com jaqueta de couro e direção de pose')}${photo('luz-em-foco-grid-luz-em-foco-21','Retrato de estúdio com sombras gráficas')}</div></section>
<section class="section testimonials light" id="depoimentos"><div class="section-heading"><div><p class="eyebrow">02 / QUEM VIVE, SENTE</p><h2>O que fica <em>além da foto.</em></h2></div><p class="placeholder-note">Prévia de layout<br>Depoimentos ilustrativos</p></div><div class="testimonials-grid">${[
['“Eu queria fotos profissionais. Saí com uma nova forma de enxergar a minha própria imagem.”','Sobre a experiência'],
['“Da maquiagem à direção das poses, cada detalhe me fez sentir à vontade diante da câmera.”','Sobre o cuidado'],
['“O resultado tem a minha personalidade e a presença que eu queria transmitir no meu trabalho.”','Sobre o resultado']
].map(([quote,caption],i)=>`<article class="quote-card"><span class="quote-mark" aria-hidden="true">“</span><blockquote>${quote}</blockquote><div class="quote-person"><span class="person-monogram">${String(i+1).padStart(2,'0')}</span><div><strong>Nome da cliente</strong><span>${caption} · texto ilustrativo</span></div></div></article>`).join('')}</div></section>
<section class="section courses-section" id="cursos"><div class="section-heading"><div><p class="eyebrow">03 / APRENDA COMIGO</p><h2>O meu olhar.<br><em>O seu próximo nível.</em></h2></div><p>Da luz ao último detalhe da edição.<br>Conheça os caminhos para transformar<br>a sua forma de fotografar.</p></div><div class="course-grid">${[
['beauty-edit','beauty-edit-hero-thaina-beauty-edit','01 / EDIÇÃO DE IMAGEM','Beauty Edit','O refinamento que transforma uma boa foto em uma imagem extraordinária.','R$ 297'],
['boss-4p','boss-4p-hero-thaina-boss-4p','02 / MÉTODO COMPLETO','Boss 4P','Posicionamento, produção, performance fotográfica e pós-produção.','R$ 997'],
['luz-em-foco','luz-em-foco-hero-thaina-luz-em-foco','03 / ILUMINAÇÃO','Luz em Foco','Domine a luz. Crie atmosferas. Dê uma nova dimensão aos seus retratos.','R$ 297']
].map(([slug,img,cat,name,desc,price])=>`<a class="course-card" href="/${slug}/"><div class="course-image">${photo(img, `Thainá Sampaio na apresentação do curso ${name}`, {sizes:'(max-width: 700px) 90vw, 33vw'})}<span class="round-arrow" aria-hidden="true">↗</span></div><div class="course-info"><p class="eyebrow">${cat}</p><h3>${name}</h3><p>${desc}</p><div class="course-card-bottom"><span>${price} <small>à vista</small></span><span>Conhecer curso ↗</span></div></div></a>`).join('')}</div></section>
<section class="section about-section light" id="sobre"><div class="about-copy"><p class="eyebrow">04 / POR TRÁS DAS LENTES</p><h2>Muito prazer,<br><em>Thainá.</em></h2>${biography}<span class="signature">Thainá Sampaio</span><p class="eyebrow">MAQUIADORA, FOTÓGRAFA & MENTORA</p></div><div class="about-image">${photo('beauty-edit-thaina-perfil-beauty-edit','Thainá Sampaio, maquiadora, fotógrafa e criadora do Pacote Boss')}<span class="about-image-label">Um olhar que transforma.</span></div></section>
<section class="section contact-section" id="contato"><div class="contact-copy"><p class="eyebrow">05 / VAMOS CONVERSAR</p><h2>A sua próxima<br>imagem começa<br><em>com um olá.</em></h2><p>Quer agendar seu Pacote Boss ou saber mais sobre os cursos? Me conte o que você tem em mente.</p><a class="text-link" href="#contact-form" data-whatsapp="Olá, Thainá! Vim pelo site e gostaria de conversar.">Fale comigo pelo WhatsApp ${arrow}</a></div><form id="contact-form"><div class="form-row"><label for="name">Seu nome<input id="name" name="name" autocomplete="name" placeholder="Como posso te chamar?" required maxlength="100"></label><label for="phone">Seu WhatsApp<input id="phone" name="phone" type="tel" autocomplete="tel" inputmode="tel" placeholder="(00) 00000-0000" required minlength="10" maxlength="24"></label></div><label for="email">Seu e-mail <span class="optional">(opcional)</span><input id="email" name="email" type="email" autocomplete="email" placeholder="voce@exemplo.com" maxlength="200"></label><label for="interest">Sobre o que vamos conversar?<select id="interest" name="interest" required><option value="">Selecione uma opção</option><option>Pacote Boss — ensaio fotográfico</option><option>Curso Beauty Edit</option><option>Curso Boss 4P</option><option>Curso Luz em Foco</option><option>Outros assuntos</option></select></label><label for="message">Sua mensagem<textarea id="message" name="message" rows="3" placeholder="Me conte um pouco sobre você e o que procura…" required maxlength="2000"></textarea></label><p class="form-note">Ao continuar, sua mensagem será preparada no WhatsApp. O envio é feito por você, na conversa.</p><button class="button" type="submit">Continuar no WhatsApp ${arrow}</button><p id="form-status" class="form-status" role="status" aria-live="polite"></p></form></section>
`);
