export const arrow = '<span aria-hidden="true">↗</span>';
export function photo(slug, alt, { eager = false, cls = '', sizes = '(max-width: 700px) 100vw, 50vw' } = {}) {
  return `<img class="${cls}" src="/assets/img/${slug}-1200.webp" srcset="/assets/img/${slug}-640.webp 640w, /assets/img/${slug}-1200.webp 1200w, /assets/img/${slug}-2000.webp 2000w" sizes="${sizes}" alt="${alt}" width="1200" height="1800" ${eager ? 'fetchpriority="high" loading="eager"' : 'loading="lazy"'} decoding="async">`;
}
export function header(active = '') {
  return `<a class="skip-link" href="#conteudo">Pular para o conteúdo</a><header class="site-header"><a class="brand" href="/" aria-label="Thainá Sampaio, início"><img src="/assets/logo.svg" alt="Thainá Sampaio Studio" width="300" height="60"></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation" aria-label="Abrir menu"><span></span><span></span></button><nav id="navigation" aria-label="Navegação principal"><a href="/#pacote-boss">Pacote Boss</a><a href="/#cursos" ${active ? 'class="active"' : ''}>Produtos</a><a href="/#sobre">Sobre mim</a><a href="/#contato">Contato</a><a class="button button-small" href="/#contato" data-whatsapp="Olá, Thainá! Quero saber mais sobre o Pacote Boss.">Vamos criar juntos ${arrow}</a></nav></header>`;
}
export function footer() {
  return `<footer class="site-footer"><div class="footer-top"><a class="brand" href="/" aria-label="Thainá Sampaio, início"><img src="/assets/logo.svg" alt="Thainá Sampaio Studio" width="300" height="60"></a><div><a href="/#pacote-boss">Pacote Boss</a><a href="/#cursos">Produtos</a><a href="/#sobre">Sobre mim</a><a href="/#contato">Contato</a></div><a class="back-top" href="#top">Voltar ao topo ↑</a></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Thainá Sampaio. Todos os direitos reservados.</span><span>Fotografia, beleza e um novo olhar sobre você.</span></div></footer>`;
}
export function layout(title, description, body, page = '', { noindex = false } = {}) {
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#171715"><title>${title}</title><meta name="description" content="${description}">${noindex?'<meta name="robots" content="noindex, nofollow">':''}<link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/css/style.css"><script defer src="/assets/js/config.js"></script><script defer src="/assets/js/main.js"></script></head><body class="${page}" id="top">${header(page)}<main id="conteudo">${body}</main>${footer()}</body></html>`;
}
export const biography = `<p>Sou Thainá Sampaio, maquiadora, fotógrafa e mentora. Há mais de 11 anos, meu trabalho conecta beleza e fotografia para realçar o que cada pessoa tem de único.</p><p>Foi desse encontro que nasceu o Pacote Boss: uma experiência que une maquiagem e retratos com direção, cuidado e intenção. Da escolha dos looks à expressão diante da câmera, cada detalhe faz parte da imagem que queremos construir.</p><p>Hoje, compartilho nos meus cursos o que desenvolvi em estúdio e nos atendimentos reais. Para que outros profissionais também possam criar imagens que comunicam presença e valor.</p>`;
